export type stockdocumentsType = {
  url: string;
  year: number;
  course: number | null;
  semestr: number | null;
  teacher: string | null;
  subject: string | null;
  title: string | null;
  special: boolean;
};

export const stockdocuments = [
  {
    url: 'https://drive.google.com/file/d/10_p4gRnhjW5BdaXNGwnGvAcr2OV-DW-y/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 1,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1zcPgmVM6OrsQR9fhHhhwePeRKYHx_s0hAeDpVJj9VwM/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 1,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1z_LTHxqPgURAf1s7SAG2LfKdqwXJwnh3gPErqxOtB5Q/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 1,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: true,
  },
  {
    url: 'https://kpfu.ru/staff_files/F704331925/algebra1_1.pdf',
    year: 2018,
    course: 1,
    semestr: 1,
    teacher: 'Ильин',
    subject: 'Алгебра и геометрия',
    title: 'методичка',
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/18mii6-5zD320HzV33QgaheBj6KyQS03w/view?usp=sharing',
    year: 2017,
    course: 1,
    semestr: 1,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: 'зачем и коллоквиум',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1fsPXJi2ewBF--19LrC5TFIQoPVrUEcY-9wVcNbKcCu0/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 1,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: 'зачет',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1Y8xvEe0q2q29BpgftWy7GqhCdALkEZVk6r2Fb3VV5IU/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 1,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: 'коллоквиум',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1IFEuxXlqCr1-g7Tu35z_qwjrcaE7rGKiSWxlMhcWf7k/edit?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 1,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: 'зачет',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/16v1lWhBX5uDDDkFbw3tGUSZG95xBCojE5Ju7AVPmVLc/edit?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 1,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: 'коллоквиум',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1-5WEqRX4qHhwXOmssXek0DMq3rjbi3KfUv3kAzSD29Y/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 1,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: 'зачет',
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/13tIav9w6IP9b3IxToFj7Kn9joWci3n7GHe2IdgyoP7s/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 1,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: 'зачет',
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/1kazpVhjqUMklHXKHTylgqesHOdg8RWo_Wj0Tjlr47Cw/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 1,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1uoU5vBBoWCqhDo9No2n2KvuKaRP11Rgh4FJ7wHSA1s0/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 1,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1b1ELo04WOo6Gjo2svVuKXFdzd1LYV1ykCEkF6i1H-IY/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 1,
    teacher: 'Скворцова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1pJXMSEcowHROrKDUElRf4fNcgKiREZbfS9ACGov3j_I/edit?usp=sharing',
    year: 0,
    course: 1,
    semestr: 1,
    teacher: 'Скворцова',
    subject: 'Математический анализ',
    title: null,
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/14mm4-dtKruugz--2RLsy6rWpx1VZQLaUFtchsF_oPN4/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 1,
    teacher: 'Скворцова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1BLpzoq0cYoSsCi7Ze6WBgOA8hEoZmnlonk7C3Cqt8I8/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 1,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/1H4olx_XtpLo4vHrLQDODZKuC3xM7k-Sy/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 1,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1oIDWP1WBbDRFcnW-4ibXWsE58dKe3xnn8jlaYLD-KSU/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Салимов',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1afNicEAV9wZ73DVB1-KxxfQaPOl6C5qLGUfVf2ckcdo/edit?usp=sharing',
    year: 2019,
    course: 1,
    semestr: 2,
    teacher: 'Салимов',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1GxagHzpYz9gEwXabzdRkJeByCVaqfikb-hkU9kUm2XE/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/1ZF_CymdLraNMIjgKYJCZfqlWUXoDDm2EMoiHJ_FlSyw/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1LFLDoNot-ICm3wgT-Kd7ufUFAVw7k9vvGyUeXxp3upw/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1ydO8iJE5eLX51kjj_nXlyI986RsEeLyjERIUtbGZx_Q/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: false,
  },
  {
    url: 'https://www.notion.so/2021-1-9126f81a548744ea8e27ed2123ad0955?pvs=4',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'notion',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1AiBlT94IVFSlP-InGtnM9vzNehhcFd3E',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'презентации',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1c8DAn7V24C0_mnwrn5e4bp05N2qMalWJ0PtyLi_L5VA/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'вопросы с экзамена',
    special: false,
  },
  {
    url: 'https://www.youtube.com/playlist?list=PL5cBwNxdeNv3-7PSnzS8fv0BWdC3Gbdca',
    year: 2020,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'записи лекций',
    special: false,
  },
  {
    url: 'https://www.youtube.com/playlist?list=PLmVX4EnY5L-V5UaSlH6v0LlafQojptFO7',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'записи лекций',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1BrkVOXbodPIPMZWfC6cxormBmaAePuzVI-I0oSAdUko/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'кривой конспект',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/11GWSiWnoER6OsjJpW94OMR_rCtvTmN5EQjaT1tWjDaQ/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'быстрые вопросы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1kU10NYFpto5FGLyGIbucl8RMHjZM3M-kdMCngdgSJ7U/edit?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: 'гайд по сортировкам',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1GvKXWmqNnkhFDCXoxKPrB3_QVPZxKF256jANwBeEgWM/edit?usp=sharing',
    year: 2019,
    course: 1,
    semestr: 2,
    teacher: 'Хадиев',
    subject: 'Алгоритмы и структуры данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1HLseg_qUlOBP8NLpnG3UjT1_pJpOhx1WHrmfd4mtS70/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/1ShuVIdx-CMeOe4ty2_f79d2rZYKUFmuoA4qn6dtprFk/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1mJ9yr8L2yGuiDashduHSqD3lXbKNEfDjA0aJ3gAZFsw/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1cUEka-PN7up9DJCxgFkYGX6C8VE1OrN6mVZ8ol3H2tc/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1ygY921CPgEsECfFErQgFAgQWkbYYBi9PT8ykQbnzEuw/edit?usp=sharing',
    year: 2019,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/1u3K5SWT16Smb39c_dehFb7OHzWibKWas/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1TWZVynAhs0zZGsdsKVeIGKm8JgcuDQGeCOq3SbF73pg/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1dlKyMImFRn-6TK9EHUZZAXhHnjCcdkm3?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: 'кривые конспекты',
    special: false,
  },
  {
    url: 'https://vk.com/doc127439390_552504491?hash=kQ5kSjkEGLP8KdXB4oAidndp4iXXOawSGUzIAWbSm10&dl=Pny7gscqAHBYWPEHh1ZzM0YIdCQvdyYnCzRvvhZ0LmT',
    year: 2020,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: 'билеты 902 группы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1JDq4wUgJ3Q3k6nH2oYG4Odd770TjVMkPqdGWD456msk/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Арсланов',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/15cX4v5qHdh5sPDjsMLv0I4sdpOX30x7YRf2DYisGheA/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Ильин',
    subject: 'Алгебра и геометрия',
    title: null,
    special: false,
  },
  {
    url: 'https://vk.com/doc133480686_606407163?hash=LJP6cRUYybMzZ4V4qpd6magzazZ3EDdK8mc7fvzzp6o&dl=ZVpFlopQX4z7mRPtsM291TQN7towFvCwbLSodorTPjo',
    year: 2020,
    course: 1,
    semestr: 2,
    teacher: 'Ильин',
    subject: 'Алгебра и геометрия',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1TZRSYBf2PxlQiPc1rPzGvBlw05Qw3B27ToYbiCEy-rc/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Ильин',
    subject: 'Алгебра и геометрия',
    title: 'сливы',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1Ox7Y40m8JzcT3dR9JygoisuPK33feOoo?usp=drive_link',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1-7KirxFqvLef8ovc1yUFOQTrEiVY88NW?usp=drive_link',
    year: 2019,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1ecKWwlyWxFtlInDA4kNdJG4AfSs3Jv4YXerjZeKbWCU/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/1go76gTUVw4h083-30G_Qq96zWazzGkDF/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1kQ7m4b9KynXvDme4hUJlf-R4snPiY62MURNATy-fEjA/edit?usp=sharing',
    year: 2019,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: 'сливы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1XWJy_lNVWFPZFAn51pwDQG9sgnwp1CZdORcjHVEAKWw/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: 'сливы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1WPpSj9Aogo8J1CqpxPBSb7TGzI0IMh1b3docmxUUpv8/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Зубков',
    subject: 'Дискретная математика',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/11Ib93kdI9_ds1YpxSP-DZ7DdpE6b6Hy8/edit?usp=sharing&ouid=115368225887290137384&rtpof=true&sd=true',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Калимуллин',
    subject: 'Дискретная математика',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1mVlwkmXzCRZ40N-J6jPJgvi6Lr7dQbgZDiqaNdpMcIw/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Калимуллин',
    subject: 'Дискретная математика',
    title: null,
    special: true,
  },
  {
    url: 'https://drive.google.com/file/d/1go76gTUVw4h083-30G_Qq96zWazzGkDF/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 2,
    teacher: 'Корнеева',
    subject: 'Дискретная математика',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1WeYysAUViLwJZKMqqSNP8TXmZkNFs4jm6tLn5_JFuco/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1gRaOH2VZD1XFLoY82cwvoDOahUfp6QQpJA5RrJgyqCQ/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1cHfem8aUKPkkHgqbjjSSY0dHO0Qr5B7No5LFZ-ap2LY/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/16L9bXCdCpspDmcsK6qoEe0fMi9MoZDy9Uf0HnL7uPI0/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1vfHVHqyOm36TDfSn3oOcSOKK7bjvy0H8Vn4-3RksCks/edit?usp=sharing',
    year: 2020,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/12VtoP55bOxSk3Bpxirj5O9dkOV5pbfqvCvxdwLPm1u4/edit?usp=sharing',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/15dxkfKQUWx8FgXsBkGTCYsYc59FpX60EXJlN15baOeA/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Информатика и программирование',
    title: null,
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/1naa-tgiLmmglCM2BYLEQqvYZqn4EA163/edit?usp=sharing&ouid=115368225887290137384&rtpof=true&sd=true',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Липачев',
    subject: 'Информатика и программирование',
    title: null,
    special: true,
  },
  {
    url: 'https://docs.google.com/document/d/1EhmmuAcZUlscDJxgxK4cwCivfjxxLvmqjrjVfpdHOm8/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Скворцова',
    subject: 'Математический анализ',
    title: 'обязательные определения',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/198MqlztQV1l-XDjiLoXwx0hR07WofhamtnJp3oMXN9M/edit?usp=sharing',
    year: 2019,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1GjE91YLxAMDxXGVaptTqVpTBBkglOiYrMV6cMLgaeaA/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1B07rXu5TVWdvdUGDn3rcJFsUf3WMmAdH?usp=drive_link',
    year: 2022,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: 'кривые конспекты',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/11MhT3TFs-vD53LHNcRugH1RfRIZhnQ7YGBZKAEFMJa8/edit?usp=sharing',
    year: 2021,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: 'сливы',
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/1KEjBEVZ8xQ2HjFX4OTPaN7C94Npj5Luu/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: 'методичка',
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/17k_ax76SCez8Fsndki-bN1O2X8rXKXSP/view?usp=sharing',
    year: 2018,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1al25Dv5uZeLLwIFHgffnqSvCOB0zSCOeMctuAT3SnIQ/edit?usp=sharing',
    year: 2023,
    course: 1,
    semestr: 2,
    teacher: 'Широкова',
    subject: 'Математический анализ',
    title: 'сливы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1v8gyO1ukKkGu69pVM9aPKI7HhYP2DWdLHTMFtYxUOT8/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PL5cBwNxdeNv0hfymnuhfpmzb0-z6d57jJ',
    year: 2019,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLNfH5NDl0aJWlIMg5jkRPR5375_wyORnG',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1_k8-01MACZuJT4kM6An39hlY4V1QGudP6Z88PLjx_GU/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: 'контрольные',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1CEPVuYUVPnLwQeztmkCEm200KuEWSU6jel4yoeS1R0Q/edit?usp=sharing',
    year: 2020,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: 'контрольные',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1m8-z85gNV2WgE0nkxV9gJrqUwr1j8JwkVdp3i-LMS-4/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: 'дз по olap',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1bpr0cCyoI50sFzscvrfglV8Z3_e05jO0t_9Dj-wqLsw/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1XW3-H8B79mu2kMcNR678iRUJ64MgRcb-6D-HptW7fuQ/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/15Ts9LJW1nAW1BBdT4CrxbzcPAdIMhM7LhEZayO94p04/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: 'устные вопросы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1v8gyO1ukKkGu69pVM9aPKI7HhYP2DWdLHTMFtYxUOT8/edit?usp=sharing',
    year: 2019,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1TdmmLujutVn3hqBWGgQSfa62w3ddENMBdTYINtTjsC0/edit?usp=sharing',
    year: 2018,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1tLL31uklduy2zxDWg3-ToLPDUmfChqcMuLcEZaLXML4/edit?usp=sharing',
    year: 2019,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1cWgEnZkr211ZfB541kuYPjxMGvipPV27i4FznnOsKAw/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Якупов',
    subject: 'Базы данных',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1-HBIPwIxBXyCWEwmHjLL9RWBiJhnMxm-?usp=drive_link',
    year: 2019,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://youtu.be/Hiht8uAF24Q',
    year: 2016,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'курс huawei',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/11wvGb_mMp1wE2StZowRZrTgqWGnOeSwg10LuPpuev2E/edit?usp=sharing',
    year: 2019,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: null,
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLmVX4EnY5L-XKYBhpZ_HNgen6-WWPblYd',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PL9JS5P4sWrqrSffk4nM_fB72CsGNKzv92',
    year: 2020,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1Sfvwv79TqSiwX4fLt2_2lfjIwaIv1alnhhnly4j2kGg/edit?usp=sharing',
    year: 2018,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1FaFwBb4e4TEfPO2dWisbYDv6zSqOgVdKyPS3f04IpMc/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1aW0nTEE94H65RGKqHZ6Ls7-A54AQQ4_pGdJ-H6Wzv-4/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1f__9_6_Jbvu7C6G8XaFC-Zr7Vc4Dyjy6?usp=drive_link',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Абрамский',
    subject: 'Основы разработки информационных систем',
    title: 'презентации',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1DVC0cZ7gLXkz-zR2gJrcxPVdBbYWYPQN4W5W7dPFADE/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Абрамский',
    subject: 'Основы разработки информационных систем',
    title: 'python',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1yUDsoZNsTR3aasue5oAWIfFfxl5ux54BgvdBLCekh5Q/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Абрамский',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1-su9e58IpzcOo9gAaP6SDYeLRWHGKCYJRPc2s2WCxj4/edit?usp=sharing',
    year: 2020,
    course: 2,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1UEN40sXo6crSKR96WJX546hwvTqwIDg_E75Rhr59ftc/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1aF1MjSgbN1p9Eg5HuFEL9Z80s6YqlOrgXo2el3kX93U/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Основы разработки информационных систем',
    title: 'практика',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/15inl1_2VjyFls8M8nkuyRFELXV07EuEPn3VuaAcXxCE/edit?usp=sharing',
    year: 2020,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1GJdd79M2YbPnNRZstBvHONCCOkbCqp5ZCaIk8gNoS_4/edit?usp=sharing',
    year: 2020,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/13hefO-VIUMcMn075B1a9i6JzEorYjwVD?usp=drive_link',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'презентации',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLL50Gk4AUYCMIwcqptUJ2BgYUFppJ9WQD',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLNfH5NDl0aJU7lPmXkLiIeibSxPzhR-of',
    year: 2021,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1gGagMwUnbH7Q6DxlpQqepKMz874LkXesnxoMvKhJpig/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1yPiDwQoGeMxIIR9RdkTbQe3ubMFDC1j74HfVNCuxz14/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/19kbnvkz349M86QN0c_m0NPsUpwyG1NBbkOR2W1V4khc/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1wkxSvPQAcneSesIHkdoq13yudikuJ30Fne6ccH72srI/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1-j8fbMZT2InCIpeLNKRFGXxHCnusiBgmsBmtFr5FGHU/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1-16pWjHMaQ4GWqi7M8jfRDLfEoYtoupd?usp=drive_link',
    year: 2019,
    course: 2,
    semestr: 1,
    teacher: 'Григорьева',
    subject: 'Теория вероятностей',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLNfH5NDl0aJUwnlD0FMIsRlVcpZil2kjs',
    year: 2022,
    course: 2,
    semestr: 1,
    teacher: 'Григорьева',
    subject: 'Теория вероятностей',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1qYUO6DmVrRwGYtb1Xa94ctN8Qy2_HaVBT4ta2_x61dg/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 1,
    teacher: 'Григорьева',
    subject: 'Теория вероятностей',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/18_d38DhgxbzNFgb6Vxtwltdge8Ass58a5e1uXCldheU/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'ответы на тест huawei',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1-HBIPwIxBXyCWEwmHjLL9RWBiJhnMxm-?usp=drive_link',
    year: 2019,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'конспект',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1JKGLGLtl1hL5jiKtFuYOlau9XyqvKW2KjgibF9bLARQ/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'непонятный док',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PL7CmqnO_Qydi3QWXMUFnBGUuYgIlRQd63',
    year: 2016,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'непонятные лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1Inds6wQGES1UPyJn3RQwHE0D4OcL1dRD8m1enQKyQI4/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'лабы',
    special: false,
  },
  {
    url: 'https://docs.google.com/spreadsheets/d/1MKafDMxPcE6fv6eb_7W3JMI4GDp-TWd5W9zSq2u0QG0/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'непонятная таблица',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1cEvXgntCwRS9mXkLtU0VVMby2ZbQC3I_3ODrKG_fPfY/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'контрольные',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1FW8wzqGI5KByPrCzdXB88tmSq3aDYDVjfSYVxM8yAE0/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'контрольные',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/13uT-CClJqMNH66GKGcISRb96qYjDiHTEcvteNzJeuQk/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/18_d38DhgxbzNFgb6Vxtwltdge8Ass58a5e1uXCldheU/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1I-4mK_7f_3UCzDv2BrIGvEi8A9VyxivQt5Sd7_S5loQ/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Максютин',
    subject: 'Вычислительные системы, сети и телекоммуникации',
    title: 'лабы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1haHKO5ETtIi3Or2Wi4PV3PPR02-Nwi2lulJEbccZSns/edit?usp=sharing',
    year: 2023,
    course: 2,
    semestr: 2,
    teacher: 'Абрамский',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://youtu.be/s1IRSMkH9vU',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 1',
    special: false,
  },
  {
    url: 'https://youtu.be/V3R-iaAhNBw',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 2',
    special: false,
  },
  {
    url: 'https://youtu.be/tkVCjpUfvK0',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 3',
    special: false,
  },
  {
    url: 'https://youtu.be/lSyYy0YWmsg',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 4',
    special: false,
  },
  {
    url: 'https://youtu.be/J6P5bD8e5N8',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 5',
    special: false,
  },
  {
    url: 'https://youtu.be/ZA2K7jYmdz0',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 6',
    special: false,
  },
  {
    url: 'https://youtu.be/cZ4IK53-EGE',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция 7',
    special: false,
  },
  {
    url: 'https://youtu.be/nEiT4XvCmCI',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Сидиков',
    subject: 'Основы разработки информационных систем',
    title: 'лекция',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/13XlxTJJx69vmLXpcRThh9HI6zOn6bwK22CvQRW73YZw/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/19mw_EKghjxxNPBNIQ-XhAPJhIqTN41ppM-WKW-7IelA/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'блиц',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1bbhTtEpJ_oUUcBCCV4Rg5e_meEzboTFV60SR8N0i_TE/edit?usp=sharing',
    year: 2021,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'контрольная',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1tSRTjxwtiTdt49i3pHyfdsZkxM-cEqz8L6D6d3Qi5DI/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/19FXuMVm60oUUmGgozUi_odC5kcP0eLBLCYoKXAMk1Lg/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/14k3kMNeO-U7XcR6kzNXjnG4MkWksP2Fofk91ahuUCto/edit?usp=sharing',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: null,
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLyUmZAMKExIISiaQUPibbmLf_7cQRa80m',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://github.com/ist-programming/java4-examples',
    year: 2022,
    course: 2,
    semestr: 2,
    teacher: 'Ференец',
    subject: 'Основы разработки информационных систем',
    title: 'github',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1OQUTm19lzLbxWOHY8vnEL6LachafAyQemnSNyLrLIqY/edit',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Крылова',
    subject: 'БЖД',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1Mgglp0wrg1g60rMI78b2VgGjYPowcNSUn6v1nZJyWJk/edit',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Крылова',
    subject: 'БЖД',
    title: 'презентации',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1VmE40toEislzZgvNFibEJBf3Q0Two581mVaT9W3QrM4/edit#',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Крылова',
    subject: 'БЖД',
    title: 'презентации',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1rqcc7SFlcQD-s3XCK_QGj3qldjf0mR096zx1vR1EFuQ/edit#',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Крылова',
    subject: 'БЖД',
    title: 'презентации',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1XItaMCSwivMUDkTzrf9zYjeBDQdxzJ1hGFuek30xTRo/edit',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: 'тест 1',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1RywuSp2jYc6oLkkPBlrz7hMgS1Qc_sZmIbtrNzaYpMY/edit?usp=sharing',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: 'тест 2 и тест 3',
    special: false,
  },
  {
    url: 'https://github.com/renett-t/operating-systems-2022-23',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: 'github',
    special: false,
  },
  {
    url: 'https://github.com/pingvi28/Operating-systems_laboratory-work',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: 'github',
    special: false,
  },
  {
    url: 'https://www.youtube.com/playlist?list=PLbUGLDQvckP_QMsD_0jvHUOfXSOZbmhOF',
    year: 2021,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLyUmZAMKExILAT4myPZN8R-8hoa_9nSod',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1BVQTipr6R4xB5E-aS8w4h683Bv17elik3EMuX_37a5M/edit?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Валиуллин',
    subject: 'Операционные системы',
    title: null,
    special: false,
  },
  {
    url: 'https://stepik.org/course/115024/promo',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Насрутдинов',
    subject: 'Параллельное программирование',
    title: 'stepik',
    special: false,
  },
  {
    url: 'http://rsusu1.rnd.runnet.ru/tutor/method/m2/page03.html',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Насрутдинов',
    subject: 'Параллельное программирование',
    title: 'Базы mpi',
    special: false,
  },
  {
    url: 'https://github.com/pingvi28/Parallel-programming',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Насрутдинов',
    subject: 'Параллельное программирование',
    title: 'github',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/14K0znmb95DuYxK4H8L_SE2LWGFHIt99Tesd6YC78OZM/edit?usp=share_link',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Насрутдинов',
    subject: 'Параллельное программирование',
    title: 'отчет mpi',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1-FA1k-vp72RvGQC6RYasB99xmkrpS04i?usp=drive_link',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1ZRT3ldF1ut-JvaUUq57fuIIcNa5b6-DL?usp=drive_link',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/1wwGzwZtaGGkFeCrGnWOLY7jJ2Og4MA0q/view?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/1lDPICbG0_abB2Q7Ey2TYVkuJ7N-5DnVI/view?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'контрольная',
    special: false,
  },
  {
    url: 'https://drive.google.com/file/d/16sn3lil_Gwug-TUJIigeUNIILUvKpk2R/view?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'контрольная',
    special: false,
  },
  {
    url: 'https://vk.com/doc133480686_660172110?hash=60WkeTueLlY4OZe46ZARykPyLQ1D1zbTslcxAKNtxP4&dl=W0TZneUQbIN0bkuZhryAWmNesKTS5ZAupBx2lzggjT8',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: null,
    special: false,
  },
  {
    url: 'https://vk.com/doc133480686_660172632?hash=2wkZVpolaptyNrUm8fLxKe0vLExQuHIYwYJAt1utz5o&dl=rXd4UQn0AsNno5IyLebfKpsSwq12wuqlUbOkwlz1R7D',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'http://www.mou.mipt.ru/AddDiscAn.pdf',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'http://ivt.omgtu.ru/wp-content/uploads/2017/10/teoriya-informacii-i-codirovaniya.pdf',
    year: 2015,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'https://miigaik.ru/vtiaoai/%D0%A8%D0%B0%D0%B2%D0%B5%D0%BD%D1%8C%D0%BA%D0%BE%20%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%20%D1%82%D0%B5%D0%BE%D1%80%D0%B8%D0%B8%20%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20519bf9657cf3c1cd4326082d4f8c6e0d.pdf',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'http://www.unn.ru/books/met_files/Graphs.pdf',
    year: 2017,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'https://stepik.org/lesson/93446/step/1?unit=69396',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'stepik',
    special: false,
  },
  {
    url: 'http://cito-web.yspu.org/link1/metod/theory/node36.html',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'http://www.mou.mipt.ru/AddDiscAn.pdf',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLbUGLDQvckP8aA5yVAk_weldY9kA-ardk',
    year: 2021,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLdj0yYpBfMsuU09w1VTSmgg8IGDbC7Z0c',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'лекции',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1BtteMMypzQnPvQAcCrp1K2daKTK6uvhzhVKbNG0t1eU/edit?usp=sharing',
    year: 2021,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1-nZ2BgLfZhBEvx24nFiHUZLHSdcbruOe/edit?usp=sharing&ouid=115368225887290137384&rtpof=true&sd=true',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'контрольная',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1opYmk7V_yexEND6QcTAACKCqnlbyKMKejbO9zNxynn4/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1e2317mmtHcaIQ4m0E6qpixAm73_SSRXzhZToW9FExwc/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'сливы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1NWHOyPnTCu6sM-W673wNg9JY24fb-MtHwfdvCEXnzqw/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1IQjo6wqqA1lp90i9ECmb5XA_7qx4eJthvohkFVaf290/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1Tcl-QovlKqM1Mj5lhfsXTMbYLxx0QGSZyLSsj68HZB8/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'вопросы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1v_dJbasgf81U_f8fZWordPj8VGIBOcQdLNEzxtB5IAs/edit?usp=sharing',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'вопросы',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1W-TfRScAN20N--NFh-nI4ZryfTcd_hEubxI8jbLzWxo/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'билеты',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1bzuKEzOdjZplk9F3sqQx_Lh28xV-zQPT4g4lG6okA5c/edit?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1a7cwLaFox_wlo5gom1_9PuTeN0VcQtXtv0DY_THvpgc/edit?usp=sharing',
    year: 2017,
    course: 3,
    semestr: 1,
    teacher: 'Салимов',
    subject: 'Теория информации и кодирования',
    title: 'теория',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/140fVwVkORl5iXRNZpTTnpYsngk9uc0gy?usp=drive_link',
    year: 2021,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1keo2EM-_E7RpTdC0EgzXgtVyFSA2TmoP?ths=true',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: 'автотесты',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/140fVwVkORl5iXRNZpTTnpYsngk9uc0gy',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: null,
    special: false,
  },
  {
    url: 'https://vk.com/away.php?to=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1o_rTcG72d0w7KqN4q4yWK3c-zrgSbV38Y_AjBYCSQgY%2Fedit&cc_key=',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1cC1IdHd6NuG-OX5yGJeGxz1doWJk8xAENkBbXTZtMw0/edit',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: 'тест 1',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1_NO4PSLsZI8MHUpxnETvnYkEVG-Km338eD81uDRpbLs/edit',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: 'тест 2',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1wexJdGIAA1jbVa1Ut2yettw5aSWguG5wpcAaQ2G5q6w/edit#heading=h.5b8dp5z3snu9',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: 'багрепорт',
    special: false,
  },
  {
    url: 'https://docs.google.com/presentation/d/1XOCPxvX8HryYsH3UflfkBFH1gFocG3Eqg7pP01Fxvuc/edit#slide=id.ge7b5133482_0_0',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: 'доклад',
    special: false,
  },
  {
    url: 'https://docs.google.com/spreadsheets/d/1-ayeViKeHqgJSSHRZjpc-awYRFY1fJ89xGdgXlg_gEk/edit#gid=0',
    year: 2020,
    course: 3,
    semestr: 1,
    teacher: 'Ильина',
    subject: 'Управление качеством разработки ПО',
    title: 'темы докладов',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/114Qo3RmGRukVdwWry0m9VbPNcmGk7f6o_gM-PLolJ-4/edit?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Ахметшина',
    subject: 'Экономика',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1hYsx2uKZZ2S3_xPqt5HCXitNULppfSMNnGGbEoDHKzE/edit?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Ахметшина',
    subject: 'Экономика',
    title: null,
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1LGev0QtcCNuohbSJz4y6DtOGoIbrRep8?usp=drive_link',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Ахметшина',
    subject: 'Экономика',
    title: 'конспекты',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1ubxmUp10juEbbwsqZHnZ58aWcDaw1fneBMZXwBtu-K8/edit?usp=sharing',
    year: 2022,
    course: 3,
    semestr: 1,
    teacher: 'Ахметшина',
    subject: 'Экономика',
    title: 'летучка',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1UJemjBWxhrwhMbJ2DUnKCp22hf9zu3qTqzxXUzH2Spc/edit?usp=sharing',
    year: 2023,
    course: 3,
    semestr: 2,
    teacher: 'Иванов',
    subject: 'Информационная безопасность',
    title: null,
    special: false,
  },
  {
    url: 'https://vk.com/doc133480686_667553881?hash=bxViIYRTbXjIEzbegzp49OElriLOaZNJYcwaKcpljZc&dl=0PBuFOqcAlGQ9U5m09Uundw1iPGN1zo9pScPu8QPjY4',
    year: 2023,
    course: 3,
    semestr: 2,
    teacher: 'Иванов',
    subject: 'Информационная безопасность',
    title: null,
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1Cczyfa0DnIDNcbHIzzqlavmBuKBNSqosYsm-GgS88sQ/edit?usp=sharing',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'андроид',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1KBIcId_3CO8CC-JwFjrLf417eX8REZSv?usp=drive_link',
    year: 2022,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: '3 курс',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLNfH5NDl0aJU__O_GCehJTrbsnbSqDrxb',
    year: 2022,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'математическая статистика',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1UQDcgfswGEjhXZPrTD2ef-CBzJ6-sFLneW3yfECnOqs/edit?usp=sharing',
    year: 2022,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'ux-аналитика',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1HdYk_pNhMDxtiFLZ0R0wj5-_nqYmiIHFWQjM5o1kTJE/edit?usp=sharing',
    year: 2017,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'ux-аналитика',
    special: false,
  },
  {
    url: 'https://trello.com/b/nZF398wY/javalab-2020-2021',
    year: 2020,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'javalab trello',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1G8NdYgwnjmEsmdHbvwRTw2hELJUbjfk1cyD86CQ4lAA/edit?usp=sharing',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'javalab',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1b1QCYZY1ql6m5TH-oBqGuja76PIhqxyRsiYYuKaXKE4/edit?usp=sharing',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'java аршинов',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PLbUGLDQvckP9ck5qxfW1P-mnM8p5dBnGZ',
    year: 2020,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'django абрамский',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PL1r_JHvO3VtBxvtfVCOoiwEA5KPBbfgaG',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'django абрамский',
    special: false,
  },
  {
    url: 'https://www.youtube.com/playlist?list=PLzSIvl7IRPWSZ74VUbfH6fcHITGB15W2P',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'android 1 сем',
    special: false,
  },
  {
    url: 'https://www.youtube.com/playlist?list=PLzSIvl7IRPWTnFweYMLdvUSgx1e2IQ0Rp',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'android 2 сем',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1gpGo3fcw5nScsHIvz5ta_TZxkv9eM3Ythq2x7Ct7N-0/edit?usp=sharing',
    year: 2023,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'машинное обучение',
    special: false,
  },
  {
    url: 'https://docs.google.com/document/d/1ILNOI2Dj1ZhTx6cahUgpT0P4YR25Ql7HakYp6GUjqcs/edit?usp=sharing',
    year: 2020,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'общий док',
    special: false,
  },
  {
    url: 'https://youtube.com/playlist?list=PL5cBwNxdeNv3-4-j7P5S6PVrfW18zL99G',
    year: 2021,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'лекции халиуллина',
    special: false,
  },
  {
    url: 'https://drive.google.com/drive/folders/1jjr_do0Ar7DtjyVYeUEmrhsUo57c2tlO?ths=true',
    year: 2020,
    course: null,
    semestr: null,
    teacher: null,
    subject: null,
    title: 'жизненный цикл',
    special: false,
  },
];
